### ISSUE TITLE
Empty pages after update

### ISSUE THREAD

**Issue by piegamesde** [gildas-lormeau/single-filez-cli#3]
I updated to the latest commit, and now all the archived pages don't load anymore (remain blank). This may be related to the fix of https://github.com/gildas-lormeau/SingleFileZ/issues/142.

**Comment by gildas-lormeau** [comment]
I cannot reproduce the issue. What does the saved page contain? For example, is there some HTML? Can it be unzipped?

**Comment by piegamesde** [comment]
The saved page looks fine – both in html and as zip – but when opening it remains blank.

`./single-filez --browser-executable-path chromium "https://github.com/gildas-lormeau/single-filez-cli/issues/3" ./tmp.html`

 
Output: [tmp.html](https://github.com/gildas-lormeau/single-filez-cli/files/10123636/tmp.zip) (renamed to .zip because GitHub is stupid)

**Comment by gildas-lormeau** [comment]
If you're using Chrome to view the page, you need SingleFileZ to be installed and make sure it is enabled for the filesystem. In the past, a message was displayed when it happened. Maybe, that's the regression.

**Comment by piegamesde** [comment]
I viewed it both in Firefox (where it used to work) as well as through a local webserver (where it should be guaranteed to work). Blank page. Old version works fine.

**Comment by gildas-lormeau** [comment]
I don't understand the cause of your problem. Your page works fine for me in Chrome and Firefox.

**Comment by gildas-lormeau** [comment]
However I confirm the regression, i.e. the fact that the warning message is not displayed if SingleFileZ not installed or if it can't access pages from the filesystem in Chrome (and Safari probably).

**Comment by piegamesde** [comment]
When opening the file in Firefox, the console shows the following error message: "The byte stream was erroneous according to the character encoding that was declared. The character encoding declaration may be incorrect." Is this maybe an issue?

**Comment by gildas-lormeau** [comment]
No, this error is displayed on my end as well. It's not the cause of the blank page.

**Comment by gildas-lormeau** [comment]
Sorry, I confirm the issue. It does not work when SingleFileZ is disabled in Firefox...

**Comment by gildas-lormeau** [comment]
This should be fixed in the new version I've just published.

**Comment by piegamesde** [comment]
Well, at least it shows a "Please wait..." now, however the console logs "Uncaught ReferenceError: Nn is not defined" so I guess it won't progress any further from there :/

**Comment by gildas-lormeau** [comment]
It should work now.

**Comment by piegamesde** [comment]
Yes it does. Many thanks again.
