### ISSUE TITLE
Don't bundle the JavaScript

### ISSUE THREAD

**Issue by piegamesde** [gildas-lormeau/single-filez-cli#9]
I occasionally run into pages whose JavaScript doesn't appreciate being archived *at all*. Is there a way to run the page with JavaScript enabled but to simply not bundle any of the scripts? Or to load an archived page without any of its JavaScript (I can't disable JavaScript entirely since it is also needed to load the bundled resources …)

**Comment by gildas-lormeau** [comment]
These are the default settings actually. The option `--block-scripts` is `true` by default, which means that scripts should not be saved. You can also use `--save-raw-page` to save the page without interpreting it.

Finally, you could also integrate use a userscript for more advanced usages, see https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved for more info. It also works with the CLI but the userscript comments are ignored.

**Comment by piegamesde** [comment]
Oh, I see. Turns out I set `--block-scripts=false` because I generally want JavaScript to be executed before archiving. This is totally a user error on my side, however I'd argue that this distinction would be made a bit more clear in the documentation and the description of the CLI flags

**Comment by gildas-lormeau** [comment]
I wasn't aware of the ambiguity, thank you for pointing it out. I'll update the doc. By the way, `single-filez-cli` is deprecated. You should use `single-file-cli` (without the "z") which is able to do the same thing and especially with up-to-date code.
